spring.application.name=farmacia-salud-api

# Configuración dinámica para Railway (Si no detecta variables, usa localhost por defecto)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bd_farmacia_salud}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Formatos de fecha y Jackson
spring.jackson.time-zone=America/Lima
spring.jackson.default-property-inclusion=non_null

# Puerto dinámico que le asigna Railway a la aplicación
server.port=${PORT:8080}
